### ISSUE TITLE
Disable auto_authorize when using SSH2() and Telnet()

### ISSUE THREAD

**Issue by FliesLikeABrick** [knipknap/exscript#123]
#62 requested a way to disable auto_authorize, and only_authenticate was added for the start and quickstart helper methods, however this doesn't help when SSH2 and Telnet are used directly.  

I am requesting that support be added to Protocol for an equivalent flag - because otherwise vanilla Exscript is not usable in our Cisco environment which provides users with privilege 15 access via RADIUS (attempting to enable looks like login failures, because it is attempting to enable when not needed or available):

[12:34:54]rrawdon@CHI-RRAWDON2:~/git/neteng-tools/unix/bgptools/cnvrbgptools$ python2 sshworker.py dtord01rtr01p
Please enter your user name [rrawdon]:
Please enter your password:

ios: Adding ssh-rsa host key for dtord01rtr01p: 3155e35a13d7fd67ff8ff6107e34e23f
ios: Attempting to authenticate rrawdon.
ios: Authenticating with _paramiko_auth_password
ios: Attempting to app-authenticate rrawdon.
ios: waiting for: ['[\\r\\n][^\\r\\n]*(?:bad secrets|denied|invalid|too short|incorrect|connection timed out|failed|failure)', 'user ?name: ?$', '(?:s\\/key|otp-md4) (\\d+) (\\S+)', '(?:[\\r\\n]Password: ?|last resort password:)$', '[\\r\\n][\\-\\w+\\.:/]+(?:\\([^\\)]+\\))?[>#] ?$']
ios: Expecting a prompt
ios: Expected pattern: <generator object <genexpr> at 0x6fff8984500>
BUFFERDUMP:
BUFFERDUMP:
dtord01rtr01p#
ios: Shell prompt received.
ios: Expecting a prompt
ios: Expected pattern: <generator object <genexpr> at 0x6fff8984b90>
BUFFERDUMP:
dtord01rtr01p#
ios: Checking '\r\ndtord01rtr01p#' for errors
ios: Calling driver.auto_authorize().
ios: Sending 'enable\r'
ios: Attempting to app-authorize rrawdon.
ios: waiting for: ['[\\r\\n][^\\r\\n]*(?:bad secrets|denied|invalid|too short|incorrect|connection timed out|failed|failure)', 'user ?name: ?$', '(?:s\\/key|otp-md4) (\\d+) (\\S+)', '(?:[\\r\\n]Password: ?|last resort password:)$', '[\\r\\n][\\-\\w+\\.:/]+(?:\\([^\\)]+\\))?[>#] ?$']
ios: Expecting a prompt
ios: Expected pattern: <generator object <genexpr> at 0x6fff8984b90>
BUFFERDUMP:
BUFFERDUMP: enab
BUFFERDUMP: enabl
BUFFERDUMP: enable
BUFFERDUMP: enable

BUFFERDUMP: enable
Password:
ios: Cleartext password prompt received.
ios: Expecting a prompt
ios: Expected pattern: <generator object <genexpr> at 0x6fff8984b90>
BUFFERDUMP: enable
Password:
ios: Sending 'userpassword\r'
ios: waiting for: ['[\\r\\n][^\\r\\n]*(?:bad secrets|denied|invalid|too short|incorrect|connection timed out|failed|failure)', 'user ?name: ?$', '(?:s\\/key|otp-md4) (\\d+) (\\S+)', '(?:[\\r\\n]Password: ?|last resort password:)$', '[\\r\\n][\\-\\w+\\.:/]+(?:\\([^\\)]+\\))?[>#] ?$']
ios: Expecting a prompt
ios: Expected pattern: <generator object <genexpr> at 0x6fff8984b90>
BUFFERDUMP:
BUFFERDUMP:
% Access denied

dtord01rtr01p#
Exception in thread thread-dtord01rtr01p:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "sshworker.py", line 48, in _start
    c.login(self.account)
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 630, in login
    self.auto_app_authorize(app_account, flush = flush)
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 880, in auto_app_authorize
    self.get_driver().auto_authorize(self, account, flush, bailout)
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/drivers/ios.py", line 54, in auto_authorize
    conn.app_authorize(account, flush, bailout)
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 854, in app_authorize
    self._app_authenticate(account, password, flush, bailout)
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 739, in _app_authenticate
    raise LoginFailure("Login failed: %s" % msg)
LoginFailure: Login failed: Buffer: '\r\n% Access denied'

As you can see, it is getting to a priv 15 (#) user prompt immediately after providing the user credentials, but experiencing failure when attempting to enable.

**Comment by FliesLikeABrick** [comment]
#124  opened with my proposed solution

**Comment by FliesLikeABrick** [comment]
Disregard - this can be accomplished by using authenticate() instead of login()
