### ISSUE TITLE
pkg_resources.DistributionNotFound on pip or make install

### ISSUE THREAD

**Issue by jakestec** [knipknap/exscript#125]
Hello, iv been running into an issue with getting exscript installed on a new box. If I install via pip or manually pull the source from git and use make I get the same error when trying to use exscript.

```
Traceback (most recent call last):
  File "/usr/local/bin/exscript", line 4, in <module>
    __import__('pkg_resources').run_script('Exscript===v2.1.507-gc052a59', 'exscript')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Exscript===v2.1.507-gc052a59' distribution was not found and is required by the application
```

I did some searching but I can't seem to find a solution. Any help would be appreciated, thanks!

**Comment by knipknap** [comment]
That looks like PIP can't find your Exscript installation. I recommend checking that

- the package is installed in a location that PIP can find, and
- the files are all readable by the user that runs the script.
