### ISSUE TITLE
Exscript not installable in plain virtualenv

### ISSUE THREAD

**Issue by soerenbe** [knipknap/exscript#141]
Hi there,
we currently test your library in our project. We figured out following bug:

**Steps to reproduce on (at least) Ubuntu 16.10, 16.04, Debian Jessie:**

```
[zeus@olymp ] /tmp$ cd /tmp/

[zeus@olymp ] /tmp$ virtualenv exscript_bug
Running virtualenv with interpreter /usr/bin/python2
New python executable in /tmp/exscript_bug/bin/python2
Also creating executable in /tmp/exscript_bug/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

[zeus@olymp ] /tmp$ source exscript_bug/bin/activate

(exscript_bug) 1 [zeus@olymp ] /tmp$ python --version
Python 2.7.12

(exscript_bug) [zeus@olymp ] /tmp$ pip --version
pip 9.0.1 from /tmp/exscript_bug/local/lib/python2.7/site-packages (python 2.7)

(exscript_bug) [zeus@olymp ] /tmp$ pip install exscript
Collecting exscript
  Using cached Exscript-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-HPVPnc/exscript/setup.py", line 4, in <module>
        from Exscript.version import __version__
      File "/tmp/pip-build-HPVPnc/exscript/Exscript/__init__.py", line 29, in <module>
        import paramiko
    ImportError: No module named paramiko
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-HPVPnc/exscript/
(exscript_bug) 1 [zeus@olymp ] /tmp$ 
```

**Issue**

The file `setup.py` loads the `Exscript` library:
```
(exscript_bug) [zeus@olymp ] /tmp/exscript-2.3$ cat setup.py | grep from.Exscript
from Exscript.version import __version__
```

Unfortunately the Library already loads `paramiko` in the `__init__.py`:
```
(exscript_bug) [zeus@olymp ] /tmp/exscript-2.3$ cat Exscript/__init__.py  | grep paramiko
    import paramiko
```
As a result `pip` tries to load `paramiko` already before it can read the dependencies and install `paramiko`

**Solution**

To solve this issue you should not depend on `paramiko` itself during the package setup.

Since this bug tackles your release process, I am not really able to provide a PR. But it should be easy to fix.

We would highly appreciate this fix and a new pypi release, since this is looking very promising for us. :)

Best Regards
Sören

**Comment by knipknap** [comment]
Should be fixed.
