### ISSUE TITLE
Pypi contains 2.3.1 which broken on windows. 2.3 working fine

### ISSUE THREAD

**Issue by flaurencin** [knipknap/exscript#142]
Hi,

We are definitely unlucky here, our workstations are Windows and everything got broken.
I'll try to figure it out probably account.py overriding Account.py.

But for now we have to stick to 2.3

Kind regards,

```
Collecting exscript
  Downloading Exscript-2.3.1-py2.py3-none-any.whl (370kB)
    100% |################################| 378kB 409kB/s
Requirement already satisfied: pycrypto in c:\users\ng3f1c0\anaconda2\lib\site-packages (from exscript)
Requirement already satisfied: paramiko in c:\users\ng3f1c0\anaconda2\lib\site-packages (from exscript)
Requirement already satisfied: pyasn1>=0.1.7 in c:\users\ng3f1c0\anaconda2\lib\site-packages (from paramiko->exscript)
Requirement already satisfied: cryptography>=1.1 in c:\users\ng3f1c0\anaconda2\lib\site-packages (from paramiko->exscript)
Requirement already satisfied: idna>=2.0 in c:\users\ng3f1c0\anaconda2\lib\site-packages (from cryptography>=1.1->paramiko->exscript)
Requirement already satisfied: six>=1.4.1 in c:\users\ng3f1c0\anaconda2\lib\site-packages (from cryptography>=1.1->paramiko->exscript)
Requirement already satisfied: setuptools>=11.3 in c:\users\ng3f1c0\anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg (from cryptography>=1.1->paramiko->exscript)
Requirement already satisfied: enum34 in c:\users\ng3f1c0\anaconda2\lib\site-packages (from cryptography>=1.1->paramiko->exscript)
Requirement already satisfied: ipaddress in c:\users\ng3f1c0\anaconda2\lib\site-packages (from cryptography>=1.1->paramiko->exscript)
Requirement already satisfied: cffi>=1.4.1 in c:\users\ng3f1c0\anaconda2\lib\site-packages (from cryptography>=1.1->paramiko->exscript)
Requirement already satisfied: pycparser in c:\users\ng3f1c0\anaconda2\lib\site-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko->exscript)
Installing collected packages: exscript
Successfully installed exscript-2.3.1

C:\Users\ng3f1c0>python
Python 2.7.13 |Anaconda 4.3.0 (64-bit)| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import Exscript.Account
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ng3f1c0\Anaconda2\lib\site-packages\Exscript\__init__.py", line 31, in <module>
    from Exscript.Account     import Account
ImportError: No module named Account
```

**Comment by knipknap** [comment]
This is odd, I do not see anything between 2.3 and 2.3.1 that I think might cause this to fail.

Does master work fine?

**Comment by sagslc** [comment]
I tried upgrading from 2.1.503 to 2.3.1 today and I ran into the same issue.
I downgraded to 2.3.0 and it works fine.
I found that in 2.3.1 the "account.py" has a lowercase a and in 2.3.0 and 2.1.503 "Account.py" has a capitol A.
If I have 2.3.1 installed and I change the file name from "account.py" to "Account.py" it works until you hit a different error.

**Comment by knipknap** [comment]
2.3.1 should still contain the upper case Account.py:

https://github.com/knipknap/exscript/tree/v2.3.1/Exscript

**Comment by sagslc** [comment]
I downloaded and extracted the wheel and I see that it has both the uppercase and lowercase files in it.
On windows since it treats uppercase and lowercase names as if they are the same it will overwrite one with the other when extracting.
I think this is probably the issue.

**Comment by knipknap** [comment]
Ouch, looks like a broken build, rather than broken source. I have just push 2.3.2. Please let me know if the problem persists.

**Comment by sagslc** [comment]
Works great for me now!

**Comment by knipknap** [comment]
Great, Thanks!
