### ISSUE TITLE
Exscript not working with Paramiko > 2.1.2

### ISSUE THREAD

**Issue by JuanmaNT** [knipknap/exscript#145]
Due the recent changes in Paramiko, some functions are not available (as .resource) and Exscript is Broken.

**Comment by knipknap** [comment]
This is fixed in master, can you try that?

**Comment by JuanmaNT** [comment]
Yes, it worked.
Thanks!

**Comment by 1-61803** [comment]
It doesn't seem to work with `paramiko` 2.2.1.

```
$ python
Python 2.7.13 (default, May 30 2017, 10:58:02) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import Exscript
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Exscript/__init__.py", line 34, in <module>
    from Exscript.Queue       import Queue
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Exscript/Queue.py", line 40, in <module>
    from Exscript.util.decorator import get_label
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Exscript/util/decorator.py", line 28, in <module>
    from Exscript.protocols.Exception import LoginFailure
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Exscript/protocols/__init__.py", line 28, in <module>
    from Exscript.protocols.SSH2 import SSH2
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Exscript/protocols/SSH2.py", line 34, in <module>
    from paramiko.resource      import ResourceManager
ImportError: No module named resource
>>> 
```

**Comment by knipknap** [comment]
This is fixed in master. Your traceback is from Exscript 2.3.2.

**Comment by 1-61803** [comment]
When is the next release due?

**Comment by knipknap** [comment]
Yesterday.

**Comment by 1-61803** [comment]
I see a newly uploaded wheel at PyPI — weird versioning though, but not a new release here, which is what I resorted to use.

**Comment by vikramrajsitpal** [comment]
@1-61803 can you please tell me what did you do to solve the issue?

**Comment by 1-61803** [comment]
@vikramrajsitpal, just clone master, as it's too much effort for the dev to make a new release. Or, use netmiko.

**Comment by vikramrajsitpal** [comment]
Thanks @1-61803
