### ISSUE TITLE
Connections fail using ssh2

### ISSUE THREAD

**Issue by gstewart86** [knipknap/exscript#151]
I've written a wrapper for SSH2 that builds a set of commands and then executes them all at once on a remote host. The initial connections are currently failing, however, with the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/repo/nexus/ssh.py", line 271, in get_interface
    interfaces = self.execute(commands)
  File "/mnt/c/repo/util/ssh.py", line 182, in execute
    conn.connect(self.host.address)
  File "/usr/local/lib/python2.7/dist-packages/Exscript/protocols/protocol.py", line 609, in connect
    return self._connect_hook(self.host, port)
  File "/usr/local/lib/python2.7/dist-packages/Exscript/protocols/ssh2.py", line 299, in _connect_hook
    self.client = self._paramiko_connect()
  File "/usr/local/lib/python2.7/dist-packages/Exscript/protocols/ssh2.py", line 162, in _paramiko_connect
    t.start_client()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 510, in start_client
    raise e
ImportError: /usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/_openssl.so: cannot enable executable stack as shared object requires: Invalid argument

I just recently upgraded Exscript with pip. I've tried a force-reinstall of the Exscript, cryptography, and paramiko packages.

If I can help provide any further information please don't hesitate to ask!

**Comment by gstewart86** [comment]
Discovered https://github.com/Azure/azure-cli/issues/4106, which points to an issue with the Ubuntu release I'm running. Resolving issue.

**Comment by knipknap** [comment]
Thanks for the report, and for figuring it out :-)
