### ISSUE TITLE
Fail to authenticate using SSH key

### ISSUE THREAD

**Issue by renard** [knipknap/exscript#152]
I got some issue using ssh key with Exscript:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/Exscript/workqueue/job.py", line 78, in run
    self.function(self)
  File "/usr/local/lib/python2.7/site-packages/Exscript/queue.py", line 102, in _wrapped
    result = func(job, host, conn, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/Exscript/util/decorator.py", line 47, in decorated
    return function(*(inner_args + args), **kwargs)
  File "./cidr", line 276, in do_backup_config
    if not _login(host, conn, config, devices_config):
  File "./cidr", line 251, in _login
    conn.authenticate(host.get_account(), flush = False)
  File "/usr/local/lib/python2.7/site-packages/Exscript/protocols/protocol.py", line 672, in authenticate
    self.protocol_authenticate(account)
  File "/usr/local/lib/python2.7/site-packages/Exscript/protocols/protocol.py", line 702, in protocol_authenticate
    self._protocol_authenticate_by_key(user, key)
  File "/usr/local/lib/python2.7/site-packages/Exscript/protocols/ssh2.py", line 321, in _protocol_authenticate_by_key
    self._paramiko_auth_key(user, keys, key.get_password())
  File "/usr/local/lib/python2.7/site-packages/Exscript/protocols/ssh2.py", line 246, in _paramiko_auth_key
    raise saved_exception
IOError: [Errno 2] No such file or directory: 'c'
```

This is because my key is defined using:
```python
                _key = Exscript.PrivateKey.from_file(device['key'])
```

And `device['key']` is a `basestring` type.  In [ssh2.py](https://github.com/knipknap/exscript/blob/master/Exscript/protocols/ssh2.py#L312) the check is only done against `str`.

I changed it to 
```python
        elif isinstance(key_file, (str, unicode, basestring)):
```

And it works like a charm. Is it a safe change for you?

Thanks in advance.

**Comment by knipknap** [comment]
That looks correct, and the existing code looks like some broken automatic Py3 translation. Could you attach a pull request?
