### ISSUE TITLE
Windows compatibility issue

### ISSUE THREAD

**Issue by memogharib** [knipknap/exscript#157]
good evening ,really this module is impressive and really its big efforts  :) , i just has problem related to Windows compatibility after installing at my machine , can you help me about it 

my code : 
from Exscript.protocols import Telnet
from Exscript.protocols import Account

account = Account("xxxx","XXX")
device = Telnet(debug=9)
device.connect("x.x.x.x")
device.login(account=account)

-------------------

output : 

D:\Python2.7\python.exe "D:/Gharib/Python project/test exscript.py"
Traceback (most recent call last):
  File "D:/Gharib/Python project/test exscript.py", line 5, in <module>
    device.connect("172.21.41.23")
  File "D:\Python2.7\lib\site-packages\Exscript\protocols\protocol.py", line 631, in connect
    conn = self._connect_hook(self.host, port)
  File "D:\Python2.7\lib\site-packages\Exscript\protocols\telnet.py", line 52, in _connect_hook
    rows, cols = get_terminal_size()
  File "D:\Python2.7\lib\site-packages\Exscript\util\tty.py", line 119, in get_terminal_size
    close_fds=True)
  File "D:\Python2.7\lib\subprocess.py", line 347, in __init__
    raise ValueError("close_fds is not supported on Windows gharib "
ValueError: close_fds is not supported on Windows gharib platforms if you redirect stdin/stdout/stderr

**Comment by memogharib** [comment]
thankssssss so much , its working now :) :)
