### ISSUE TITLE
Exscript install issue

### ISSUE THREAD

**Issue by Ryuksapple** [knipknap/exscript#159]
Trying to install exscript and I am seeing the following. Looking for some help here:

zipimport.ZipImportError: bad local file header in /usr/local/lib/python2.7/site-packages/Exscript-2.4.35-py2.7.egg
make: *** [install] Error 1

[sugoi1 exscript]$ make tests
cd tests/Exscript/; ./run_suite.py 1
Traceback (most recent call last):
  File "./run_suite.py", line 110, in <module>
    unittest.TextTestRunner(verbosity=verbosity).run(recursive_suite())
  File "./run_suite.py", line 96, in recursive_suite
    return load_suite(find('.', '*Test.py'))
  File "./run_suite.py", line 80, in load_suite
    module = __import__(name, globals(), locals(), [''])
  File "/home/semalhotra/exscript/exscript/tests/Exscript/AccountManagerTest.py", line 8, in <module>
    from Exscript.account import Account, AccountPool, AccountManager
  File "/home/semalhotra/exscript/exscript/tests/Exscript/../../Exscript/__init__.py", line 30, in <module>
    import paramiko
  File "build/bdist.linux-x86_64/egg/paramiko/__init__.py", line 22, in <module>
  File "build/bdist.linux-x86_64/egg/paramiko/transport.py", line 33, in <module>
ImportError: No module named cryptography.hazmat.backends
make: *** [tests] Error 1

**Comment by knipknap** [comment]
Closing because there was no response.
