### ISSUE TITLE
Sporadic login failure when using --parallel

### ISSUE THREAD

**Issue by lathspell** [knipknap/exscript#167]
Hello

When starting Exscript with some (~50)  hosts with --parallel=5 or more, I get sporadic problems like the one below. The number increases, the higher the parallelization. Sometimes I'm lucky with no errors, sometimes 2-3. It is always different ones and the specific hosts are reachable immeately after if I connect them using SSH. The output does contain parts of the login prompt so the script did receive someting.

Any idea what could cause this? 
 
```
# exscript -l check.$(date -Is).10conns.logs --connections=10 --account-pool=/root/.exscript/adtran.pwd  --hosts=dslams-50.txt check.exscript 
Creating log directory (check.2018-08-02T10:18:39+02:00.10conns.logs)...
...
d7-o9su-116o succeeded.
d7-o9su-123o succeeded.
d7-o9su-118o succeeded.
d7-o9su-124o succeeded.
d7-o9su-113m error: Buffer: u'\r\r\nd7-o9su-113m login: \r\r\nLogin timed out after 60 seconds\r\r\n'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Exscript/workqueue/job.py", line 78, in run
    self.function(self)
  File "/usr/local/lib/python2.7/dist-packages/Exscript/queue.py", line 91, in _wrapped
    result = func(job, host, conn, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Exscript/util/decorator.py", line 117, in decorated
    conn.login(flush=flush)
  File "/usr/local/lib/python2.7/dist-packages/Exscript/protocols/protocol.py", line 674, in login
    self.authenticate(account, flush=False)
  File "/usr/local/lib/python2.7/dist-packages/Exscript/protocols/protocol.py", line 699, in authenticate
    self.app_authenticate(app_account, flush=flush)
  File "/usr/local/lib/python2.7/dist-packages/Exscript/protocols/protocol.py", line 868, in app_authenticate
    self._app_authenticate(account, password, flush, bailout)
  File "/usr/local/lib/python2.7/dist-packages/Exscript/protocols/protocol.py", line 772, in _app_authenticate
    raise TimeoutException(msg)
TimeoutException: Buffer: u'\r\r\nd7-o9su-113m login: \r\r\nLogin timed out after 60 seconds\r\r\n'

d7-o9su-113m finally failed.
d7-o9su-120o succeeded.
d7-o9su-128o succeeded.
d7-o9su-127o succeeded.
...
```

**Comment by lathspell** [comment]
Only with --protocol-verbose=5 I noticed that the default connection method was Telnet. Using SSH it works perfectly.
I'm closing this issue as using telnet in 2018 deserves punishment so no need to debug the initial problem ;-)
