### ISSUE TITLE
Cannot make exscript run

### ISSUE THREAD

**Issue by rockomano** [knipknap/exscript#184]
Hello folks,

When I'm trying to run exscript have the following result:

```
Traceback (most recent call last):
  File "/usr/local/bin/exscript", line 4, in <module>
    __import__('pkg_resources').run_script('Exscript===DEVELOPMENT', 'exscript')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 959, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycryptodomex' distribution was not found and is required by Exscript
```

I tried cloning the github repo, downloading the client but nothing seems to work.

Could you please let me know what would it be broken? Many thanks

**Comment by rockomano** [comment]
Hi @knipknap , I indeed followed up the github installation rules:

```
git clone git://github.com/knipknap/exscript
cd exscript
sudo make install
```

**Comment by knipknap** [comment]
Well, for some reason pycryptodomex is not installed, even though the setup.py and requirements.txt clearly list it. Do you have a log of the installation procedure?

**Comment by knipknap** [comment]
I see that your version says "DEVELOPMENT", which means that either you are not running the installed version, or you did not use "make install", which sets the proper version number.

**Comment by rockomano** [comment]
Thank you for the response @knipknap , I've tried once again following the github instructions (I did the "make install" command) but still had the same issue when running it, I was able to see the following output:

```
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*' found under directory 'vectors'
build/temp.macosx-10.13-intel-2.7/_openssl.c:498:10: fatal error: 'openssl/opensslv.h' file not found
#include <openssl/opensslv.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
error: Setup script exited with error: command 'cc' failed with exit status 1
make: *** [install] Error 1
```
I'm wondering this happens because I need a newer compiler version of C? I'm currently using Mac OS High Sierra
