### ISSUE TITLE
Expect and waitfor error with ValueError

### ISSUE THREAD

**Issue by sjstewart** [knipknap/exscript#225]
I'm trying to connect to a telnet server that has a Linux system connected to it, issue a newline character, and use either waitfor or expect (something using regular expressions) to match and get the output. I am able to get this to work consistently using read_until:

>>> tn.read_until(b'#', 5)
''
>>> tn.read_until(b'#', 5)
'# hithere\r\nroot@localhost:~# '

However, expect gives me this "negative seek position" error: 

>>> tn.expect(['#'], 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u/stewarts/.local/lib/python3.7/site-packages/Exscript/protocols/telnetlib.py", line 752, in expect
    return self._waitfor(relist, timeout, True, cleanup=cleanup)
  File "/u/stewarts/.local/lib/python3.7/site-packages/Exscript/protocols/telnetlib.py", line 691, in _waitfor
    self.cookedq.seek(qlen - search_window_size)
ValueError: Negative seek position -150

After seeing telnetlib is deprecated I was looking for a drop in replacement and this seemed the closest.

**Comment by knipknap** [comment]
Can you try if the problem also exists in Version a48030c?

**Comment by sjstewart** [comment]
It looks like the version I'm using does have that change to collections.py.

**Comment by dineshbaburam91** [comment]
@knipknap  Any update on this issue?  I faced the same problem when I incorporated the module with PyEZ

  File "/Users/babud/automation_development/PyEZ/pyez_vir/lib/python3.13/site-packages/junos_eznc-0+untagged.2765.geb37f93.dirty-py3.13.egg/jnpr/junos/transport/tty_telnet.py", line 112, in read_prompt
    got = self._tn.expect(_RE_PAT, self.EXPECT_TIMEOUT)
  File "/Users/babud/automation_development/PyEZ/pyez_vir/lib/python3.13/site-packages/Exscript/protocols/telnetlib.py", line 757, in expect
    return self._waitfor(relist, timeout, True, cleanup=cleanup)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/babud/automation_development/PyEZ/pyez_vir/lib/python3.13/site-packages/Exscript/protocols/telnetlib.py", line 696, in _waitfor
    self.cookedq.seek(qlen - search_window_size)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Negative seek position -150

**Comment by ppena-LiveData** [comment]
These are the changes I made to make it work for me (which is just changing `_waitfor()` to not assume that `qlen` will have a value and not assume that `search_window` will have a value, since the `self.fill_rawq()` call isn't until at the end of the `while True` loop, and that's what would fill in the buffered data):
```diff
diff --git a/Exscript/protocols/telnetlib.py b/Exscript/protocols/telnetlib.py
index 63301a1..13912a2 100644
--- a/Exscript/protocols/telnetlib.py
+++ b/Exscript/protocols/telnetlib.py
@@ -677,6 +677,7 @@ class Telnet(object):
                 self.msg('cancelling expect()')
                 return -2, None, ''
             qlen = self.cookedq.tell()
+            search_window = ''
             if cleanup:
                 while True:
                     pos = qlen-clean_sw_size-len(incomplete_tail)-head_loockback_size
@@ -691,23 +692,24 @@ class Telnet(object):
                         break
                     else:
                         clean_sw_size += search_window_size
-            else:
+            elif qlen - search_window_size > 0:
                 self.cookedq.seek(qlen - search_window_size)
                 search_window = self.cookedq.read()
-            for i in indices:
-                m = relist[i].search(search_window)
-                if m is not None:
-                    e = m.end() - m.start()
-                    e = qlen - e + 1
-                    self.cookedq.seek(0)
-                    text = self.cookedq.read(e)
-                    if flush:
+            if search_window:
+                for i in indices:
+                    m = relist[i].search(search_window)
+                    if m is not None:
+                        e = m.end() - m.start()
+                        e = qlen - e + 1
                         self.cookedq.seek(0)
-                        self.cookedq.truncate()
-                        self.cookedq.write(search_window[m.end():])
-                    else:
-                        self.cookedq.seek(qlen)
-                    return i, m, text
+                        text = self.cookedq.read(e)
+                        if flush:
+                            self.cookedq.seek(0)
+                            self.cookedq.truncate()
+                            self.cookedq.write(search_window[m.end():])
+                        else:
+                            self.cookedq.seek(qlen)
+                        return i, m, text
             if self.eof:
                 break
             if timeout is not None:
```
