### ISSUE TITLE
Exscript.protocols.exception.TimeoutException: Error while waiting for response from device

### ISSUE THREAD

**Issue by Faerie1999** [knipknap/exscript#239]
hi, with following code,I get the error timeout:
```
conn = Telnet()
conn.connect(ip, port)
conn.login(read_login())
conn.execute('uname -a')
```

but using terminal，input telnet ip port,I can remote control the device.why?

Traceback (most recent call last):
  File "/Users/admin/docker/k8s_jenkins/SmartAPI/.venv/lib/python3.12/site-packages/Exscript/protocols/protocol.py", line 769, in _app_authenticate
    index, match = self._waitfor(prompt_list)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/docker/k8s_jenkins/SmartAPI/.venv/lib/python3.12/site-packages/Exscript/protocols/protocol.py", line 986, in _waitfor
    result = self._domatch(re_list, False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/docker/k8s_jenkins/SmartAPI/.venv/lib/python3.12/site-packages/Exscript/protocols/telnet.py", line 99, in _domatch
    raise TimeoutException(error)
Exscript.protocols.exception.TimeoutException: Error while waiting for response from device

**Comment by AckSun** [comment]
这玩意挺难用，因为python3不支持telnetlib了，想测试替代方案Exscript和telnetlib3。目前我找到两种方式登录，
```
if __name__ == "__main__":
    from Exscript.protocols import Telnet
    from Exscript.account import Account

    conn = Telnet()
    conn.connect("hostip")
    # 方法一
    conn.expect('login:')
    conn.send('username' + '\r')
    conn.expect('Password:')
    conn.send('password' + '\r')
    # 方法二
    account = Account(name='username',password='password')
    conn.login(account=account)

    conn.expect('>')
    print("成功登录到设备:")
    
    # 然后执行命令和打印
    commands = ['dis cu']
    for command in commands:
        conn.execute(command)
    response = conn.response
    print(f"Response:\n{response}\n")
    conn.close(conn)

```

最坑爹的来了，调用这个conn.execute，无论咋样都显示timeout，我都快崩溃了。最后发现一页输出的是可以显示的，只要是分页的输出，需要打空格那种，就是会显示timeout！！！我不知道这个是在文件中调选项还是什么，不过这确实有点坑了，我用telnetlib的时候完全没有这个问题。
