### ISSUE TITLE
Arista port ID's that include subports not compatible

### ISSUE THREAD

**Issue by nottings** [knipknap/exscript#61]
I'm noticing that our Arista ports with subports do not jive with Exscript. Could you build in support for this.  An example failure is included below.

sNJEQ01#configure terminal
sNJEQ01(config)#interface Ethernet50/1
sNJEQ01(config-if-Et50/1)#sNJEQ01 error: Timeout while waiting for response from device

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Exscript/workqueue/Job.py", line 64, in run
    self.function(self)
  File "/usr/lib/python2.7/site-packages/Exscript/Queue.py", line 80, in _wrapped
    result = func(job, host, conn, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/Exscript/util/decorator.py", line 110, in decorated
    return function(job, host, conn, *args, **kwargs)
  File "/opt/autoconfint/lib/python2.7/site-packages/autoconfint/models.py", line 44, in execute_commands
    conn.execute(sendcommand)
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 888, in execute
    return self.expect_prompt()
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 987, in expect_prompt
    result = self.expect(self.get_prompt())
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 968, in expect
    result = self._expect(prompt)
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 944, in _expect
    result = self._domatch(to_regexs(prompt), True)
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/SSH2.py", line 327, in _domatch
    if not self._fill_buffer():
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/SSH2.py", line 303, in _fill_buffer
    raise TimeoutException(error)
TimeoutException: Timeout while waiting for response from device

sNJEQ01 finally failed.

**Comment by egroeper** [comment]
In my opinion, this is resolved.
