### ISSUE TITLE
Weird error with older device

### ISSUE THREAD

**Issue by markomo** [knipknap/exscript#65]
Error:
```
Traceback (most recent call last):
  File "exscript test.py", line 17, in <module>
    conn.login(account)
  File "C:\Python27\lib\site-packages\exscript-development-py2.7.egg\Exscript\protocols\Protocol.py", line 594, in login

    self.authenticate(account, flush = False)
  File "C:\Python27\lib\site-packages\exscript-development-py2.7.egg\Exscript\protocols\Protocol.py", line 617, in authe
nticate
    self.protocol_authenticate(account)
  File "C:\Python27\lib\site-packages\exscript-development-py2.7.egg\Exscript\protocols\Protocol.py", line 643, in proto
col_authenticate
    self._protocol_authenticate(user, password)
  File "C:\Python27\lib\site-packages\exscript-development-py2.7.egg\Exscript\protocols\SSH2.py", line 267, in _protocol
_authenticate
    self._paramiko_shell()
  File "C:\Python27\lib\site-packages\exscript-development-py2.7.egg\Exscript\protocols\SSH2.py", line 256, in _paramiko
_shell
    raise LoginFailure('Failed to open shell: ' + str(e))
Exscript.protocols.Exception.LoginFailure: Failed to open shell: Channel closed.
```
Code: 
```
from Exscript.util.interact import read_login
from Exscript.protocols import SSH2
import time
import re

account = read_login()
host = raw_input("Please type the hostname: ")

commandfile = open('commands.txt')
p = re.compile(ur'(.+?)\n')
active = commandfile.read()
commands = re.findall(p, active)
commandfile.close()

conn = SSH2()
conn.connect(str(host))
conn.login(account)

for cmd in commands:
	print "current command: ",cmd
	conn.execute(str(cmd))
	print "Response was:", conn.response
	time.sleep(1)



conn.send('exit\r')
conn.close()
```

It works fine with other hosts, and the host I am trying it against works with putty when forced to SSH v1 and v2

**Comment by egroeper** [comment]
I really don't understand how ```SSH2(debug=5)`'` could throw an error with current master.
Which version of exscript are you running and which error are you getting?

This definitely looks like a problem with paramiko and not exscript itself.

**Comment by egroeper** [comment]
Closing because I got no answer.
Reopen, if you have further information.
