### ISSUE TITLE
Does not work on MAC or CentOS6.5

### ISSUE THREAD

**Issue by autumnw** [knipknap/exscript#68]
Hi,

I installed master brach code on macos and CentOS6.5, got the same error with simple demo code:

>>> conn.login(account)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Exscript-DEVELOPMENT-py2.7.egg/Exscript/protocols/Protocol.py", line 606, in login
    self.authenticate(account, flush = False)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Exscript-DEVELOPMENT-py2.7.egg/Exscript/protocols/Protocol.py", line 629, in authenticate
    self.protocol_authenticate(account)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Exscript-DEVELOPMENT-py2.7.egg/Exscript/protocols/Protocol.py", line 655, in protocol_authenticate
    self._protocol_authenticate(user, password)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Exscript-DEVELOPMENT-py2.7.egg/Exscript/protocols/SSH2.py", line 266, in _protocol_authenticate
    self._paramiko_auth(user, password)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Exscript-DEVELOPMENT-py2.7.egg/Exscript/protocols/SSH2.py", line 245, in _paramiko_auth
    raise LoginFailure('Login failed: ' + str(last_exception))
Exscript.protocols.Exception.LoginFailure: Login failed: ('Bad authentication type', [u'publickey', u'keyboard-interactive', u'hostbased']) (allowed_types=[u'publickey', u'keyboard-interactive', u'hostbased'])

**Comment by egroeper** [comment]
I don't know, why login fails.
Please run with debug output enabled to get more information about what the problem is:
```
from Exscript.util.interact import read_login
from Exscript.protocols import SSH2
account = read_login()
conn = SSH2(debug=1)
conn.connect('localhost')
conn.login(account)
conn.execute('ls -l')
print "Response was:", repr(conn.response)
conn.send('exit\r')
conn.close()
```

**Comment by egroeper** [comment]
Please reopen, if you have further information. With such little information I can't do anything.

I just successfully tested on CentOS 6.5 using vagrant:
```
yum update
yum install git python-crypto python-setuptools python-devel
git clone https://github.com/knipknap/exscript.git
cd exscript/
sudo make install PREFIX=/usr
cd demos/simple/
python simple.py
```

This results in:
```
python simple.py 
Please enter your user name [vagrant]: 
Please enter your password: 
Response was: 'ls -l\r\ntotal 4\r\ndrwxr-xr-x 9 root root 4096 Jan 16 16:48 exscript\r\n[vagrant@localhost ~]$ '
```
