### ISSUE TITLE
Ran "make tests" gave errors

### ISSUE THREAD

**Issue by shahharsh12** [knipknap/exscript#88]
root@ashok-virtual-machine:/home/ashok/CL/exscript# make tests
cd tests/Exscript/; ./run_suite.py 1
....................................................................................................................................................................................................Process SSHd-177:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ashok/CL/exscript/tests/Exscript/../../src/Exscript/servers/Server.py", line 105, in _run
    self._shutdown_notify(conn)
  File "/home/ashok/CL/exscript/tests/Exscript/../../src/Exscript/servers/SSHd.py", line 121, in _shutdown_notify
    self.channel.send('Server is shutting down.\n')
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 698, in send
    return self._send(s, m)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/channel.py", line 1058, in _send
    raise socket.error('Socket is closed')
error: Socket is closed
.Process SSHd-178:

**Comment by egroeper** [comment]
exscript is currently not compatible with paramiko >=1.15.0.
See #79.
