### ISSUE TITLE
Cisco IOS Enable doesnt work if "Service linenum" is configured. OLD Issue #57

### ISSUE THREAD

**Issue by compyy** [knipknap/exscript#98]
Hello,

Sorry i am back i thought you would never reply.

So i changed the script again like this and same issue, if Service line number is enabled this script doesnt work.
# ! /usr/bin/python

from Exscript.util.interact import read_login
from Exscript.protocols import SSH2
from Exscript.protocols.drivers import ios
import Exscript.util.file as euf
import Exscript.util.start as eus

hosts = euf.get_hosts_from_file('hosts.txt')
# accounts = get_accounts_from_file('accounts.cfg')

accounts = read_login()

def do_something(job, host, conn):
conn.execute('term len 0')
conn.execute('who')

print conn.response
# conn = SSH2()

eus.start(accounts, hosts, do_something, max_threads=2)

output:
yasir@iou-vm:~/Documents/PyIOS$ python PyIOS.py
Please enter your user name [yasir]: id961723
Please enter your password: 
bru-11-r200 error: Buffer: '\r\nbru-11-r200 line 4 \r\n\r\nbru-11-r200>'
Traceback (most recent call last): 
  File "/usr/local/lib/python2.7/dist-packages/Exscript-v2.1.479_g0eaaa87-py2.7.egg/Exscript/workqueue/Job.py", line 64, in run
    self.function(self)
  File "/usr/local/lib/python2.7/dist-packages/Exscript-v2.1.479_g0eaaa87-py2.7.egg/Exscript/Queue.py", line 91, in _wrapped
    result = func(job, host, conn, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Exscript-v2.1.479_g0eaaa87-py2.7.egg/Exscript/util/decorator.py", line 105, in decorated
    conn.login(flush = flush)
  File "/usr/local/lib/python2.7/dist-packages/Exscript-v2.1.479_g0eaaa87-py2.7.egg/Exscript/protocols/Protocol.py", line 630, in login
    self.auto_app_authorize(app_account, flush = flush)
  File "/usr/local/lib/python2.7/dist-packages/Exscript-v2.1.479_g0eaaa87-py2.7.egg/Exscript/protocols/Protocol.py", line 879, in auto_app_authorize
    self.get_driver().auto_authorize(self, account, flush, bailout)
  File "/usr/local/lib/python2.7/dist-packages/Exscript-v2.1.479_g0eaaa87-py2.7.egg/Exscript/protocols/drivers/one_os.py", line 43, in auto_authorize
    conn.app_authorize(account, flush, bailout)
  File "/usr/local/lib/python2.7/dist-packages/Exscript-v2.1.479_g0eaaa87-py2.7.egg/Exscript/protocols/Protocol.py", line 853, in app_authorize
    self._app_authenticate(account, password, flush, bailout)
  File "/usr/local/lib/python2.7/dist-packages/Exscript-v2.1.479_g0eaaa87-py2.7.egg/Exscript/protocols/Protocol.py", line 723, in _app_authenticate
    raise TimeoutException(msg)
TimeoutException: Buffer: '\r\nbru-11-r200 line 4 \r\n\r\nbru-11-r200>'

**Comment by egroeper** [comment]
Old request for this is #57.

**Comment by egroeper** [comment]
I'm sorry. To help you with this I really need you to run this with debugging enabled. Using Queue doesn't help, but complicates things.
Please try your first version of the code with `conn = SSH2(debug = 1)`.

**Comment by FliesLikeABrick** [comment]
I am experiencing the same, amongst some other complications.  Here is the requested output with debug=1:
generic: Adding ssh-rsa host key for rtr-edge1.sv1.cnvr.net: d13450dd9f4e0db6390bf66902d97d06
generic: Attempting to authenticate rrawdon.
generic: Authenticating with _paramiko_auth_password
generic: Attempting to app-authenticate rrawdon.
generic: Expecting a prompt
one_os: Protocol: driver replaced: generic -> one_os
one_os: Protocol.app_authenticate(): driver replaced
one_os: Expecting a prompt
one_os: Shell prompt received.
one_os: Expecting a prompt
one_os: Calling driver.auto_authorize().
one_os: Attempting to app-authorize rrawdon.
one_os: Expecting a prompt
one_os: Cleartext password prompt received.
one_os: Expecting a prompt
one_os: Expecting a prompt
Exception in thread thread-rtr-edge1.sv1.cnvr.net:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "sshworker.py", line 48, in _start
    c.login(self.account)
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 630, in login
    self.auto_app_authorize(app_account, flush = flush)
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 879, in auto_app_authorize
    self.get_driver().auto_authorize(self, account, flush, bailout)
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/drivers/one_os.py", line 43, in auto_authorize
    conn.app_authorize(account, flush, bailout)
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 853, in app_authorize
    self._app_authenticate(account, password, flush, bailout)
  File "/usr/lib/python2.7/site-packages/Exscript/protocols/Protocol.py", line 738, in _app_authenticate
    raise LoginFailure("Login failed")
LoginFailure: Login failed

**Comment by knipknap** [comment]
I agree with Enno, the content of the buffer looks like something that the default prompt regex should match:

`_prompt_re   = [re.compile(r'[\r\n][\-\w+\.:/]+(?:\([^\)]+\))?[>#] ?$')]
`

So I think we need a proper log with debug level 2 at least. Since this is very old I am closing the bug, but feel free to reopen if you can send a log.
